### ISSUE TITLE
Strand-specific information

### ISSUE THREAD

**Issue by piazza-lab** [js2264/tinyMapper#2]
Hi Jacques, I love your tinyMapper, it's so useful and simple for calibrated ChIP-seq.
I was wondering whether you could implement a "strand-specific" layer in the code, that would provide information on which strand is chipped for instance (For instance in this paper: https://pubmed-ncbi-nlm-nih-gov.insb.bib.cnrs.fr/33651987/): in the end their could be 4 data tracks: the watson strand chip, the crick strand chip, the pooled chip (i.e. the one that is already output by tinymapper), and a watson/crick ratio. 
The calibration genome does not need to do this strand specific treatment of the data.
That would be super useful, especially since more and more people use this strand-specific protocols (like us :))

**Comment by js2264** [comment]
Hi @aurelepiazza, thanks for opening the issue and for the reference to this study. This is a nice method and clearly the resulting stranded tracks are impressive. 

Once fastq files have been mapped to a genome, one could generate stranded tracks using `bamCoverage` from `deepTools` suite, using the `--filterRNAstrand` option (even for ChIP-seq). Note that you'll have to use the opposite filter (i.e. `--filterRNAstrand reverse` for **forward** strand coverage), since this feature is normally for RNA-seq libraries for which a dUTP-based strand switch is performed. 

<img width="757" alt="image" src="https://github.com/js2264/tinyMapper/assets/19528818/3c67cb73-fa17-49ec-8b10-3c5c8b4b96a5">

That being said, I'd like to keep `tinyMapper.sh` with the least options possible, to fit the bare minimum for generic analysis, and I don't think that I will add this feature in the processing script. 

I've written a full-fledged script that you could use to process your libraries (just update the SRR IDs you want to process): 

```shell
echo -e "SRR13362137\nSRR13362138\nSRR13362139\nSRR13362146\nSRR13362147\nSRR13362148\nSRR11684712\nSRR11684713\nSRR11684714\nSRR11684715\nSRR11684716\nSRR11684717\nSRR11684718" > SRRs.txt

# - Fetch URLs
while read SRR; do 
    ffq "${SRR}" | jq -r '.[].files | map(.url)[]' >> urls.txt
done < SRRs.txt

# - Fetch metadata 
while read SRR; do 
    ffq "${SRR}" | \
        jq -r '.[].title' | \
        sed 's,.*sequencing; ,,' | \
        sed 's,: ,;,' | \
        sed 's/;/,/' | \
        sed 's,; .*,,' | \
        sed "s/$/,${SRR}/" >> metadata.csv
done < SRRs.txt

# - Fetch data
mkdir data
while read url; do 
    wget "${url}" -O data/`basename "${url}" | sed 's,_1.f,_R1.f,' | sed 's,_2.f,_R2.f,'`
done < urls.txt

# - Map data with tinymapper
mkdir results
while read SRR; do 
    tinyMapper.sh \
    --mode ChIP \
    --sample data/"${SRR}" \
    --genome ~/genomes/R64-1-1/R64-1-1 \
    --threads 12 \
    --keepIntermediate
done < SRRs.txt

# - Generate stranded tracks 
ls results/bam/genome/*/*bam > bam.txt
while read bam; do 
    out_fwd=`echo "${bam}" | sed 's,bam/genome,tracks/,' | sed 's,.bam,.FWD.CPM.bw,'`
    out_rev=`echo "${bam}" | sed 's,bam/genome,tracks/,' | sed 's,.bam,.REV.CPM.bw,'`
    out_ratio=`echo "${bam}" | sed 's,bam/genome,tracks/,' | sed 's,.bam,.FWD-vs-REV.bw,'`
    bamCoverage \
        --bam "${bam}" \
        --outFileName "${out_fwd}" \
        --binSize 1 \
        --numberOfProcessors 12 \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand reverse
    bamCoverage \
        --bam "${bam}" \
        --outFileName "${out_rev}" \
        --binSize 1 \
        --numberOfProcessors 12 \
        --normalizeUsing CPM \
        --skipNonCoveredRegions \
        --extendReads \
        --ignoreDuplicates \
        --filterRNAstrand forward
    bigwigCompare \
        --binSize 5 \
        --numberOfProcessors 12 \
        --outFileName "${out_ratio}" \
        --bigwig1 "${out_fwd}" \
        --bigwig2 "${out_rev}" \
        --skipZeroOverZero \
        --operation log2 \
        --skipNonCoveredRegions
done < bam.txt
```

(You'll also need `ffq` and `jq` as soft dependencies, on top of `tinyMapper.sh` dependencies)

**Comment by piazza-lab** [comment]
Thanks Jacques; this is perfect!
